### ISSUE TITLE
Implement sessions

### ISSUE THREAD

**Issue by valiafetisov** [makerdao-ses/switchboard-boilerplate#26]
### Goal

User can list created sessions and revoke any of them including current one

### Context

We've implemented auth in #16, but there is no logout/revoke functionality yet. In order to implement that, the suggestion is to:
- Create a table called `Session` with 
  - `id`, `createdAt`, `createdBy`, `name`
  - `referenceExpiryDate` – token expiration date stored just for the UI (the expiration should be validated via the jwt itself)
  - `referenceTokenId` – token start and end (eg `34a3...0c97`)
  - `revokedAt` – empty or a date when it was revoked
- Store `sessionId` inside jwt token (instead of the userId or in addition to?)
- Rename `getUserId` to `getUser`, use `sessionId` to check if the session is still valid, otherwise throw
- Create endpoint to list your own sessions
- Create endpoint to revoke your own token by session id
- Create endpoint to create new tokens with user-specified `name` and `expiryDurationSeconds`
- Come up with the way to distinguish user-created and sign in/sign up-created sessions (eg empty `name`)

### Tasks
- [ ] Ask questions about implementation and context, clarify implementation proposal
- [ ] Implement proposal

**Comment by KirillDogadin-std** [comment]
there's a loop in this proposal.
There're 3 actions

1. Store sessionId inside jwt token
    - needs the row created in the db because it requires `sessionId` stored inside
2. Create session row in the db:
    - due to `referenceTokenId` needed as creation arg: we have to generate token

so in the above:
  - (1) depends on (2)
  - (2) depends on (1)

which means it's not possible to create the session within single transaction.

i would suggest removing `referenceTokenId` from the db schema because jwt already safely points to the id of the session record.
  - is there a usecase for the field that i am not seeing?

**Comment by KirillDogadin-std** [comment]
there's a loop in this proposal.
There're 3 actions

1. Store sessionId inside jwt token
    - needs the row created in the db because it requires `sessionId` stored inside
2. Create session row in the db:
    - due to `referenceTokenId` needed as creation arg: we have to generate token

so in the above:
  - (1) depends on (2)
  - (2) depends on (1)

which means it's not possible to create the session within single transaction.

i would suggest removing `referenceTokenId` from the db schema because jwt already safely points to the id of the session record.
  - is there a usecase for the field that i am not seeing?

**Comment by valiafetisov** [comment]
> which means it's not possible to create the session within single transaction.

Do you mean within single SQL transaction? Or what transaction?
- Nothing forbids you from generating uuid using a library, signing it into jwt and submitting its parts to the database, as [uuid is just a default value](https://github.com/makerdao-ses/switchboard-boilerplate/blob/7cedbca0a4c8aa8f2e5123db435c76d14d54a3f3/prisma/schema.prisma#L23)
- Nothing forbids you to insert + update the record in a single [prisma transaction](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#interactive-transactions)

Otherwise, can you please elaborate on what is not possible?

> i would suggest removing `referenceTokenId` from the db schema because jwt already safely points to the id of the session record

This is not for safety, but for the improved user experience: to help the user easily identify tokens at hand, just by looking at them. Have a look at the mock https://github.com/makerdao-ses/switchboard-boilerplate/issues/24#issuecomment-1481119678

**Comment by valiafetisov** [comment]
Yes, sorry for not explicitly mentioning it! I guess to create non-expiring token one need to set `expiryDurationSeconds` as null (which will also set `referenceExpiryDate` set to null)?
